# Generated by Django 5.2.7 on 2025-11-06 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0002_transacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=25, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='metodopagamento',
            name='nome',
            field=models.CharField(max_length=25, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transacoes.categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='metodoPagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transacoes.metodopagamento', verbose_name='Método de Pagamento'),
        ),
    ]
